In [1]:
import numpy as np

In [5]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [6]:
list_of_lists = [[1,2,3], [4,5,6], [7,8,9]]
np.array(list_of_lists)
# outputs 2d array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Generate arrays

In [7]:
np.arange(0, 10)
# its like python range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 11, 2)
# all even numbers

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)
# all zeros
# outputs vektor (1d array)

array([0., 0., 0.])

In [12]:
np.zeros((5, 5))
# outputs 2d array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0, 5, 10)
# evenly spaced points from 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)
# identity matrix - number rows = columns with diagonal of 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:

np.random.rand(5)
# uniform distribution
# vektor

array([0.86758732, 0.7960744 , 0.29737528, 0.99071426, 0.47458639])

In [22]:
np.random.rand(5,5)
# 2d array

array([[0.08331859, 0.4767005 , 0.82136216, 0.27862113, 0.19424857],
       [0.77636134, 0.06667953, 0.6717328 , 0.11172308, 0.14076841],
       [0.79100611, 0.97634809, 0.13246426, 0.21860481, 0.2899963 ],
       [0.0743448 , 0.47714144, 0.45111789, 0.81966156, 0.2268194 ],
       [0.52742875, 0.72478228, 0.91732252, 0.77714861, 0.30037512]])

In [24]:
np.random.randn(2)
# normal distribution (gaussian)

array([ 1.06164961, -0.7467963 ])

In [25]:
np.random.randn(4,4)

array([[-0.70504486, -0.99346505,  0.60611951, -1.72439316],
       [-0.16489893,  0.98116953,  0.59183641, -0.15125653],
       [-1.52617035,  0.18119155,  0.55802192, -0.14383806],
       [ 0.20545893,  2.42998718, -0.90709035,  1.25625864]])

In [30]:
np.random.randint(1, 100)
# random integer from 1 to 100

41

In [31]:
np.random.randint(1, 100, 10)

array([55, 31, 71, 72, 40, 81, 80, 95, 24, 25])

Reshaping

In [32]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.reshape(5, 5) # rows, columns
# needs to sum up to 25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Min Max

In [38]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([28, 15, 28, 20, 11, 21, 11, 40,  5, 22])

In [39]:
ranarr.max()

40

In [40]:
ranarr.min()

5

In [42]:
ranarr.argmax()
# index location of max (40)

7

In [43]:
ranarr.argmin()

8

various

In [44]:
arr.shape

(25,)

In [45]:

arr.reshape(5,5).shape

(5, 5)

In [46]:
arr.dtype

dtype('int32')