In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Numpy broadcast

In [9]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr[:] = 99
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [11]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [14]:
arr_python = [1,2,3,4]
arr_python

[1, 2, 3, 4]

In [16]:
arr_python[:] = 99
# not working with normal python array

TypeError: can only assign an iterable

Indexing 2d array (Matrix)

In [20]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
arr_2d[0][0]

5

In [28]:
arr_2d[0,0]
# better than double brackets

5

In [30]:
arr_2d[:2,1:]
# all rows to 2
# all columns from 1

array([[10, 15],
       [25, 30]])

Conditional selection

In [32]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr > 5
# returns boolean array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
bool_arr = arr > 5

In [38]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [40]:
arr[arr > 5]
#same

array([ 6,  7,  8,  9, 10])

In [41]:
arr_python = [1,2,3,4,5]
arr_python

[1, 2, 3, 4, 5]

In [43]:
arr_python[arr_python>2]
# doesnt work with python array

TypeError: '>' not supported between instances of 'list' and 'int'